### ISSUE TITLE
access denied "setDatatypeConverter"

### ISSUE THREAD

**Issue by jbdujardin** [pabloo99/xmlsoccer#4]
Hi!

I have this error when I'm using your jar file (version 0.0.2) in java project : 
access denied ("javax.xml.bind.JAXBPermission" "setDatatypeConverter")

I'm not Java developer and I don't find fix :(

Thx for your help

**Comment by pabloo99** [comment]
Hi!

Please give me more details about this error. Which version of Java you are using? You received this error during calling any of methods or for every request?

**Comment by jbdujardin** [comment]
Hi!

I'm on Mac OS X 10.11.2 (El Capitan), I use Java SDK 1.8 and my IDE is IntelliJ IDEA.

I have this error for all methods.

This is my code : 

XmlSoccerService xmlSoccerService = new XmlSoccerServiceImpl();
xmlSoccerService.setApiKey("MYAPIKEY");
xmlSoccerService.setServiceUrl("http://www.xmlsoccer.com/FootballDataDemo.asmx");
List<GetAllLeaguesResultDto> getAllLeaguesResultDto = xmlSoccerService.getAllLeagues();

This is the invocationTargetException : 

![xmlsoccerjava_exception](https://cloud.githubusercontent.com/assets/293027/12337940/5920e1ea-bb0d-11e5-9899-3a40ddef0e7c.jpg)

Thanks :)

**Comment by pabloo99** [comment]
I will check it.

**Comment by pabloo99** [comment]
I specified java version 1.8 with maven-compiler-plugin.
As you can see here: https://travis-ci.org/pabloo99/xmlsoccer project was build successfully on java 8 environment. Let's try with xmlsoccer version 0.0.3. I prepared small changes maybe it will help.

**Comment by jbdujardin** [comment]
Thanks for your help but I have same error with jar version 0.0.3

If you want to debug with my projet, I have put the projet on my git repository : 
http://git.jbdujardin.com/jbdujardin/XMLSoccerJava

For debugging project : 
- Launch servercode.ipr with IntelliJ IDEA
- On the console launch bin/CodeRunner
- Launch servercode (remote) module in debug mode
- Launch this request in the terminal : 
  curl -H application-id:7C55B276-B16A-AC7D-FFEA-02F8AD8A8800 -H secret-key:2E45742E-2A13-88DA-FF6A-EAC841D98900 -H Content-Type:application/json -X GET -v https://api.backendless.com/v1/data/Championnat

If you want more details you can see the Backendless doc : 
https://backendless.com/documentation/business-logic/java/

Thanks and sorry for my bad english...

**Comment by pabloo99** [comment]
@jbdujardin your problem still exists? If yes, please publish your repository once again and I will try to came back to this issue.
