### ISSUE TITLE
Odds for X1, X2, +2.5, -2.5

### ISSUE THREAD

**Issue by marcodersen** [pabloo99/xmlsoccer#5]
Hi, beautiful API you created here. I am using it since a few weeks.

Would it be a big deal to support the added odds for X1, X2, +2.5 and -2.5 goals?
That would be very very nice. Unfortunetally I am not much into spring otherwise I would create a pull request..

And big compliment for your work,
Marco

**Comment by pabloo99** [comment]
Hi, no problem. I will prepare new API version and you will get information about it.

BR,
Paweł

**Comment by pabloo99** [comment]
Done. Now method GetAllOddsByFixtureMatchId should return whole things which you are needed.
@marcodersen Please check it. Just upgrade your dependency to 0.0.4 version.

**Comment by marcodersen** [comment]
Thanks alot! Working fine.
