### ISSUE TITLE
Compatibility among different versions

### ISSUE THREAD

**Issue by dariop** [pabloo99/xmlsoccer#6]
Hi there,
I have some troubles using this library.
I used version 0.0.2
I download the latest version 0.0.5, but it seems not retrocompatible! In fact all DTOs don't have public getter for the properties. 
How can I access to these properties? Is there any documentation for that library? 
Thank you so much 

Dario

**Comment by pabloo99** [comment]
Hi! 

Which Java version you are using?
I used lombok plugin so maybe you have problem with annotation preprocessor in you dev environment?
Please take a look there: 
http://stackoverflow.com/questions/29980133/intellij-idea-cannot-see-lombok-generated-code
Unfortunately in this moment whole description for my project you have in README file.

BR,
pabloo99

**Comment by dariop** [comment]
Hi there, thank you for your answer. I solved installing lombok plugin on eclipse!

Thanks

Dario

**Comment by pabloo99** [comment]
@dariop great! So I closed this issue. In case of any questions feel free to ask.
