### ISSUE TITLE
getNextMatchOddsByLeague returns null

### ISSUE THREAD

**Issue by kvn-31** [pabloo99/xmlsoccer#7]
Hello,

I made the following call using the xmlsoccer-0.0.5.jar in java.

`List<GetOddsResultDto> getOddsResultDto = new ArrayList<>(xmlSoccerService.getNextMatchOddsByLeague("Scottish Premier League"));
        System.out.println(getOddsResultDto.toString());`

Unluckily it outputs the following:
> [GetOddsResultDto(id=null, fixtureMatchId=367778, dateCreate=2017-04-12T07:25:45.563, _10BetHomeHome=null, _10BetHomeUrl=null, _10BetHomeAway=null,.... ]

So every bookie is null. What am I doing wrong?

Best regards

**Comment by pabloo99** [comment]
Hi!

@kWinCode it looks like there was some changes in XML structure for this method and I must adapt my API. I will inform you when it will be ready.

BR,
pabloo99

**Comment by pabloo99** [comment]
It's ready! Please try it and write down comment if works correctly for you.
Now method `getNextMatchOddsByLeague` return `GetNextOddsResultDto` with all needed data.
Please use xmlsoccer version 0.0.6 .

BR,
pabloo99

**Comment by kvn-31** [comment]
Thank you! I'm really happy that you did the changes!

Just one question, how do I use the method in a right way? 

`List<GetNextOddsResultDto> getOddsResultDto = new ArrayList<>(xmlSoccerService.getNextMatchOddsByLeague("4"));
        System.out.println(getOddsResultDto.toString());`

is not working. I'm sorry if I made a major mistake, I'm new to programming.

**Comment by kvn-31** [comment]
Nvm

`ArrayList getOddsResultDto = new ArrayList<>(xmlSoccerService.getNextMatchOddsByLeague("4"));
        System.out.println(getOddsResultDto.toString());`

is working now I think. Thank you for your effort!
